### PR TITLE
Markdown CI lint action

### PR DESCRIPTION
**Pull request by photonbit**
And some typos fixed along the way :nerd_face:

### CODE REVIEW

**Comment by photonbit** [comment]
Depends on #5 for Green :heavy_check_mark:

**Review by yellowcap — APPROVED** [review]
Yeah! Did not even know that there were md linters. But of course they do! 💯

**Comment by yellowcap** [comment]
I rebased and pushed. that mixed the commit author thing a bit. sorry for that @photonbit . But the action is not running anyway at the moment.

**Comment by photonbit** [comment]
Now it is working, I added conditions so the action will be triggered on pushing to master and also when a pull request has been updated. Also the netiquette post has been formatted.

**Review by yellowcap — APPROVED** [review]
🐐

**Pull request merged**
