### PR TITLE
Remove boilerplate

### PR DESCRIPTION
**Pull request by photonbit**
All the food in the rest of the post was making me hungry and distracted :)

### CODE REVIEW

**Review by yellowcap — CHANGES_REQUESTED** [review]
Thanks! I agree to remove the authors and files, but I think at some point I made all the boilerplate posts invisible. Hence the merge conflicts. If you don't mind to rebase then I will be able to merge.

**Review by JotaFan — APPROVED** [review]
:cookie: :japanese_ogre:

**Comment by yellowcap** [comment]
Actually @photonbit , lets also remove the post's title images from the assets as part of this PR. These are no longer necessary and are tied to the boilerplate posts.
Example: https://github.com/tesselo/tesselo.github.io/blob/master/assets/images/1.jpg

**Comment by photonbit** [comment]
> Actually @photonbit , lets also remove the post's title images from the assets as part of this PR. These are no longer necessary and are tied to the boilerplate posts. Example: https://github.com/tesselo/tesselo.github.io/blob/master/assets/images/1.jpg

On it! :runner:

**Comment by photonbit** [comment]
Closing in favor of #5

**Pull request closed without merging**
